#!/usr/bin/env python3
import argparse
import os
import uuid
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate IDs for examples/basic and write a dotenv file (default: examples/basic/.env.local)."
        )
    )
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent.parent / ".env.local"),
        help="Output dotenv file path",
    )
    args = parser.parse_args()

    # Allow callers to provide their own IDs via environment.
    tenant_id = os.environ.get("ARM_TENANT_ID") or str(uuid.uuid4())
    subscription_id = os.environ.get("ARM_SUBSCRIPTION_ID") or str(uuid.uuid4())
    client_id = os.environ.get("ARM_CLIENT_ID") or str(uuid.uuid4())
    client_secret = os.environ.get("ARM_CLIENT_SECRET") or "dummy"

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    out_path.write_text(
        "\n".join(
            [
                "# Generated by examples/basic/scripts/gen_ids.py",
                f"ARM_TENANT_ID={tenant_id}",
                f"ARM_SUBSCRIPTION_ID={subscription_id}",
                f"ARM_CLIENT_ID={client_id}",
                f"ARM_CLIENT_SECRET={client_secret}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"wrote {out_path}")
    print(f"ARM_TENANT_ID={tenant_id}")
    print(f"ARM_SUBSCRIPTION_ID={subscription_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
